export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const ADD_BOOKS = "ADD_BOOKS";
export const ADD_CURRENT_BOOK = "ADD_CURRENT_BOOK";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAN_CART = "CLEAN_CART";
export const REMOVE_CURRENT_BOOK = "REMOVE_CURRENT_BOOK";
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";